version: "3"

services:
  leadmanager:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./leadmanager:/leadmanager
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000
